### ISSUE TITLE
Empty Sensor

### ISSUE THREAD

**Issue by sheckandar** [kdw2060/hassio-addons#58] opened 2024-08-07 21:28 UTC
The sensor in HA is empty even though the log suggests that the data was added.

The built-in CalDAV integration sensor is displaying all the data without errors so the issue doesn't seem to be with the caldav server. 

I'm using Open-Xchange 7.10.6 server.

HA: 2024.7.2
OS: 12.3
HA is running in a VM

```
4 entries found in caldav calendar
Fetching caldav calendar entry 8c5c69fc-32af-4295-92cc-cba4c45b4b54.ics
Fetching caldav calendar entry 601ede8f-7a95-49b4-927d-e623c9919576.ics
Fetching caldav calendar entry 957683fc-ba3c-4a87-854e-93653cd1249b.1722562040150.ics
Fetching caldav calendar entry 0c629293-089a-4fec-9cb9-390993582b5f.ics
Error fetching uri: [object Object]Request failed with status code 404
Error fetching uri: [object Object]Request failed with status code 404
Error fetching uri: [object Object]Request failed with status code 404
Error fetching uri: [object Object]Request failed with status code 404
Sorting events of calendar: ib_main
Events written to file: true. At: Wed Aug 07 2024 15:04:24 GMT-0600 (Mountain Daylight Time)
Events posted for ib_main to sensor at: Wed Aug 07 2024 15:04:24 GMT-0600 (Mountain Daylight Time)
```

**Comment by kdw2060** [comment] 2024-08-08 07:47
First thing I would do is check your configuration, does your caldavUrl have a trailing slash at the end as stated in the docs? That 404 error makes me think you might have forgotten that (then the url to fetch the ics file would be wrong).

If that does not fix the issue, I'm not familiar with Open-Xchange server I'm afraid. You'd have to reproduce the requests to fetch appointments in Postman or another tool and show me the examples.

**Comment by theclue** [comment] 2024-09-05 15:27
I'm getting insane as I have the same here: the sensor is empty.

But to me I have no errors in the logs and everything at postman level is fetched correctly.

`s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
System locale: en-US
Luxon locale set to: it-IT
System timeZone: Europe/Rome
Luxon timezone set to: Europe/Rome
Number of calendars: 1
Addon config has changed.
1 entries found in caldav calendar
Fetching caldav calendar entry 50851633-6b77-4a9a-b377-59fb32b23c20.ics
Sorting events of calendar: calendario_di_famiglia
Events written to file: true. At: Thu Sep 05 2024 17:25:23 GMT+0200 (Central European Summer Time)
Events posted for calendario_di_famiglia to sensor at: Thu Sep 05 2024 17:25:23 GMT+0200 (Central European Summer Time)`

**Comment by theclue** [comment] 2024-09-05 16:42
weird enough If i duplicate a calendar definition, the latter is empty but the aforementioned one starts populating:

<img width="1140" alt="immagine" src="https://github.com/user-attachments/assets/ea6e3d54-62fb-47af-a660-0ae7decf7b84">

**Comment by kdw2060** [comment] 2024-10-13 12:31
I'm closing this as one users' issue seems to be fixed and the other never followed up.

**Closed by kdw2060** 2024-10-13 12:31 UTC

**Comment by sheckandar** [comment] 2025-05-28 20:36
Hi,

Apologies for not responding originally as I stopped using the add-on at the time.

Now that I had time to do some troubleshooting, I found the issue to be with javascript promises, specifically `await Promise.all(fetchPromises)` returns before all processes from `ical.async.parseICS(icsData, function(err, data)` populate ics data.

There were no errors parsing the data.

The problem is clearly visible once I uncomment the following line in index.js `console.log("Parsing event " + JSON.stringify(event.summary) );`. After the event "Test1" is processed, sorting code is then fired prematurely indicating that all promises were fulfilled while the data was still being parsed, resulting in the HA sensor being either empty or having incorrect number of events.


> 4 entries found in caldav calendar
> Fetching caldav calendar entry 5d2456af-afad-46d4-bf86-037c5a33cae6.ics
> Fetching caldav calendar entry f4adc610-5103-47fa-8c4d-11ff8da95e5f.ics
> Fetching caldav calendar entry cb7a497e-287e-4b1f-b656-3a3a6d8ad32b.ics
> Fetching caldav calendar entry 3ecac4ac-6765-4b68-a1b8-e6e7e73ae7d3.ics
> Parsing event "Test1"
> Sorting events of calendar: ib_calendar
> Calendar(s) queried at: Wed May 28 2025 14:22:01 GMT-0600 (Mountain Daylight Time)
> Events written to file: true. At: Wed May 28 2025 14:22:01 GMT-0600 (Mountain Daylight Time)
> Parsing event "Test3"
> Parsing event "Test2"
> Parsing event "Test4"
> Events posted for ib_calendar to sensor at: Wed May 28 2025 14:22:01 GMT-0600 (Mountain Daylight Time)
