### ISSUE TITLE
Error updating Hass Calendar Addon

### ISSUE THREAD

**Issue by netphantm** [kdw2060/hassio-addons#55] opened 2024-02-02 17:04 UTC
[281472787969856] Error updating Hass Calendar Addon: The command '/bin/bash -o pipefail -c apt-get update && curl -s -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y --no-install-recommends tzdata=2022f-0ubuntu0.20.04.0 nodejs && npm install -g npm@10.4.0 && apt-get -y clean && rm -fr /tmp/* /var/{cache,log}/* /var/lib/apt/lists/*' returned a non-zero code: 1
got this in the log. 
supervised install on Debian 12 (bookworm), raspi 4
Do you need more info on this?

**Comment by netphantm** [comment] 2024-02-03 09:09
hm, it fixed itself somehow, don't ask me how :)

**Comment by kdw2060** [comment] 2024-02-03 14:15
It fixed itself because I pushed a fix :-)
Had missed to change a line in the dockerfile to upgrade the nodejs version. I noticed it quickly and pushed an update without updating the version number of the addon. 

If anyone still gets this error: go to the Home Assistant addon store and click the icon to search for updates, then return to the calendar addon and try to upgrade again.

**Comment by netphantm** [comment] 2024-02-03 14:53
oh, nice.. I suspected that, but wasn't sure :))
thanks a lot!

**Comment by HuLLez0r** [comment] 2024-02-09 19:27
Hi, know the issue has been marked as close

But I am still facing the the same/similar problem.

The command '/bin/bash -o pipefail -c apt-get update && curl -s -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y --no-install-recommends tzdata=2022f-0ubuntu0.20.04.0 nodejs && npm install -g npm@10.4.0 && apt-get -y clean && rm -fr /tmp/* /var/{cache,log}/* /var/lib/apt/lists/*' returned a non-zero code: 127

Any idea what might be wrong here?

**Comment by kdw2060** [comment] 2024-02-10 12:23
Hi, unfortunately i'm not a Docker expert, I just copy paste stuff I find in other examples without really understanding what all the commands do. The non zero code:127 stands for 'command not found' apparently.
I just tried locally to update all docker-related files in accordance with [this example form home-assistant](https://github.com/hassio-addons/addon-ubuntu-base/tree/main), but that results in even more errors.

I'll keep trying to find a solution. But if someone more knowledgeable with Docker and s6 reads this, please do intervene.

**Comment by kdw2060** [comment] 2024-02-20 19:59
Have not been able to find a proper solution so far. Have now just reverted the nodejs version update and pushed an updated version of the addon, this should hopefully fix the upgrade issues.

**Closed by kdw2060** 2024-02-20 19:59 UTC

**Comment by HuLLez0r** [comment] 2024-02-20 20:52
I can confirm that it works again, thanks alot
